// English, en-US
// This file was auto-generated by Quasalang

export default {
	language: `language`,
	settings: `user`,
	profile: `profile`,
	user: `user`,

	// Language
	German: `german`,
	Turkish: `turkish`,
	English: `english`,

	// Todo
	all: `all`,
	active: `active`,
	done: `done`,
}