// English, en-US
// This file was auto-generated by Quasalang

export default {
	language: `language`,
	settings: `user`,
	profile: `profile`,
	user: `user`,

	// Language
	German: `german`,
	Turkish: `turkish`,
	English: `english`,
	Italian: `italian`,

	// Todo
	all: `all`,
	active: `active`,
	done: `done`,
	creator: `creator`,

	// Settings
	user: `User`,
	roles: `Roles`,
	branches: `Branches`,

	// Tooltip
	colorModeBtn: `Switch between different brightness modes (e.g. dark and light)`,

}