// This file was auto-generated by Quasalang

import enUS from './en-US'
import deDE from './de-DE'
import trTR from './tr-TR'

export default { 
	'en-US': enUS, // English
	'de-DE': deDE, // German
	'tr-TR': trTR, // Turkish
}