// Italian, it-IT
// This file was auto-generated by Quasalang

export default {
	language: `lingua`,
	settings: `utente`,
	profile: `profilo`,
	user: `utente`,

	// Language
	German: `tedesco`,
	Turkish: `turco`,
	English: `inglese`,
	Italian: `Italiano`,

	// Todo
	all: `Tutto`,
	active: `attivo`,
	done: `Fatto`,
	creator: `Creatore`,

	// Settings
	user: `Utente`,
	roles: `Ruoli`,
	branches: `Rami`,

	// Tooltip
	colorModeBtn: `Passare da una modalità di luminosità all'altra (ad esempio scuro e chiaro)`,

}