// German, de-DE
// This file was auto-generated by Quasalang

export default {
	language: `sprache`,
	settings: `einstellungen`,
	profile: `profil`,
	user: `benutzer`,

	// Language
	German: `deutsch`,
	Turkish: `türkisch`,
	English: `englisch`,

	// Todo
	all: `alle`,
	active: `aktiv`,
	done: `erledigt`,
}