// German, de-DE
// This file was auto-generated by Quasalang

export default {
	language: `Sprache`,
	settings: `Einstellungen`,
	profile: `Profil`,
	user: `Benutzer`,

	// Language
	German: `deutsch`,
	Turkish: `türkisch`,
	English: `englisch`,
	Italian: `italienisch`,

	// Todo
	all: `alle`,
	active: `aktiv`,
	done: `erledigt`,
	creator: `Ersteller`,

	// Settings
	user: `Benutzer`,
	roles: `Rollen`,
	branches: `Filialen`,

	// Tooltip
	colorModeBtn: `wechsel zwischen verschiedenen Helligkeitsmode (z.B. Dunkel u. Hell)`,

}