// Turkish, tr-TR
// This file was auto-generated by Quasalang

export default {
	language: `dil`,
	settings: `ayarlar`,
	profile: `profil`,
	user: `kullanıcı`,

	// Language
	German: `almanca`,
	Turkish: `türkçe`,
	English: `ingilizce`,
	Italian: `italyanca`,

	// Todo
	all: `tümü`,
	active: `aktif`,
	done: `tamamlandı`,
	creator: `oluşturan`,

	// Settings
	user: `Kullanıcı`,
	roles: `Roller`,
	branches: `Şubeler`,

	// Tooltip
	colorModeBtn: `Farklı parlaklık modları arasında geçiş yapın (örneğin karanlık ve aydınlık)`,

}