// Turkish, tr-TR
// This file was auto-generated by Quasalang

export default {
	language: `dil`,
	settings: `ayarlar`,
	profile: `profil`,
	user: `kullanıcı`,

	// Language
	German: `almanca`,
	Turkish: `türkçe`,
	English: `ingilizce`,

	// Todo
	all: `tümü`,
	active: `aktif`,
	done: `tamamlandı`,
}